### ISSUE TITLE
After installation I get an error

### ISSUE THREAD

**Issue by Frits1980** [tinify/magento2-plugin#1]
After running composer and recompiling, emptying cache and redeploying static content I still get this error in the backend:

```
Invalid XML in file /data/web/magento2/vendor/tinify/magento2/etc/adminhtml/system.xml:
Element 'resource': [facet 'pattern'] The value 'Tinify_Compress_Images::tinify_compress_images' is not accepted by the pattern '([A-Z]+[a-zA-Z0-9]{1,}){1,}_[A-Z]+[A-Z0-9a-z]{1,}::[A-Za-z_0-9]{1,}'.
Line: 7

Element 'resource': 'Tinify_Compress_Images::tinify_compress_images' is not a valid value of the atomic type 'typeAclResourceId'.
Line: 7

Element 'group', attribute 'expanded': The attribute 'expanded' is not allowed.
Line: 8

#0 /data/web/magento2/vendor/magento/framework/Config/Reader/Filesystem.php(127): Magento\Config\Model\Config\Structure\Reader->_readFiles(Object(Magento\Framework\Config\FileIterator))
#1 /data/web/magento2/vendor/magento/framework/Config/Data/Scoped.php(103): Magento\Framework\Config\Reader\Filesystem->read('adminhtml')
#2 /data/web/magento2/vendor/magento/framework/Config/Data/Scoped.php(81): Magento\Framework\Config\Data\Scoped->_loadScopedData()
#3 /data/web/magento2/vendor/magento/module-config/Model/Config/Structure.php(66): Magento\Framework\Config\Data\Scoped->get()
#4 /data/web/magento2/var/generation/Magento/Config/Model/Config/Structure/Interceptor.php(14): Magento\Config\Model\Config\Structure->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#5 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Config\Model\Config\Structure\Interceptor->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#6 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Config\\...', Array)
#7 /data/web/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#8 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#9 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'configStructure', 'Magento\\Config\\...')
#10 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#11 /data/web/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#12 /data/web/magento2/vendor/magento/framework/App/ActionFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...')
#13 /data/web/magento2/vendor/magento/framework/App/Router/Base.php(300): Magento\Framework\App\ActionFactory->create('Magento\\Config\\...')
#14 /data/web/magento2/vendor/magento/framework/App/Router/Base.php(161): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#15 /data/web/magento2/vendor/magento/framework/App/FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#18 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#20 /data/web/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#23 /data/web/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /data/web/magento2/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /data/web/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#26 /data/web/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#27 {main}
```

**Comment by rolftimmermans** [comment]
Thank you for reporting! We have fixed this issue in 1.1.0.

If you run `composer update tinify/magento2` and `bin/magento setup:upgrade`, you should no longer receive this error.
